
/FinalGradeDeterminator_node:
  ros__parameters:
    CALC_GRADE_TIMEOUT: 5
    DB_CHECK_INTERVAL: 10

/ResultGenerator_node:
  ros__parameters:
    EXAM_PUBLISH_INTERVAL: 1
    MIN_MARK: 10
    MAX_MARK: 100
    
# /g425_gradecalculator_node:
  # ros__parameters:
   # Add parameters here if needed
/RetakeScheduler_node:
  ros__parameters:
    SCHEDULE_TIME: 10
   # Add parameters here if needed
/retake_grade_determinator:
  ros__parameters:
    RETAKE_GRADE: 55
  #  Add parameters here if needed
