/**:                        # Global configuration parameters for assignment 3
  ros__parameters:
    port: 5005
    tolerance: 1e-6
    timer_period_ms: 200
    connection_type: true   # false = wired, true = wireless